drivers/scsi/ufs/ufshcd-pltfrm.c: fix unused function
../../../../../../kernel/samsung/m30s-common/drivers/scsi/ufs/ufshcd-pltfrm.c:224:12: error: unused function 'ufshcd_parse_pm_lvl_policy' [-Werror,-Wunused-function]
static int ufshcd_parse_pm_lvl_policy(struct ufs_hba *hba)
           ^
../../../../../../kernel/samsung/m30s-common/drivers/scsi/ufs/ufshcd-pltfrm.c:252:12: error: unused function 'ufshcd_parse_caps_info' [-Werror,-Wunused-function]
static int ufshcd_parse_caps_info(struct ufs_hba *hba)
           ^
2 errors generated.